In [1]:
import torch
torch.__version__

'2.8.0+cpu'

#Tensors

In [2]:
#Scaler
#Scaler is a 0 dimentional tensor, it's a single number

scaler=torch.tensor(5)
# printing tensor(scaler)
scaler
# tensor dimention
scaler.ndim
# getting the item of the tensor
scaler.item()

5

In [3]:
# Vector
# vector is a 1 dimentional tensor with many numbers
vector=torch.tensor([1,2,3])
vector
# dimention of vector
vector.ndim
# shape of vector, (no of items inside vector)
vector.shape

torch.Size([3])

In [4]:
# MATRIX
# MATRIX is a combination of 2 or more vectors
MATRIX=torch.tensor([[1,2,3],[4,5,6]])
MATRIX
# dimention
MATRIX.ndim
# shape
# Above MATRIX is a shape of 2x3, 2 rows, 3 columns
MATRIX.shape

torch.Size([2, 3])

In [5]:
# Matrix example 2
MATRIX_2=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
MATRIX_2
MATRIX_2.ndim
# shape
MATRIX_2.shape
# MATRIX_2 is 3x3 matrix, for first [], 1 has come
# that means, there is a 1 dimention of 3x3 matrix


torch.Size([1, 3, 3])

#Random Tensors

In [6]:
# torch.rand()
# use to create tensor of random number
# we can pass size=(), parameter for defining size

# random tensor of size 3x4
rand_1=torch.rand(size=(3,4))
rand_1

tensor([[0.6895, 0.6675, 0.3067, 0.2277],
        [0.6974, 0.6114, 0.7614, 0.8193],
        [0.8690, 0.1489, 0.6255, 0.1906]])

In [7]:
# datatype
rand_1.dtype
# dimention
rand_1.ndim
# shape
rand_1.shape

torch.Size([3, 4])

In [8]:
rand_tensor_2=torch.rand(size=(3,3,4))
rand_tensor_2
# 3x4 matrix, repeats 3 times

tensor([[[0.9900, 0.5673, 0.9076, 0.8231],
         [0.9473, 0.2880, 0.3702, 0.1930],
         [0.8198, 0.1651, 0.7342, 0.4130]],

        [[0.3082, 0.0359, 0.4142, 0.6118],
         [0.3403, 0.3171, 0.3860, 0.1194],
         [0.9875, 0.2590, 0.0070, 0.7069]],

        [[0.8045, 0.9787, 0.9053, 0.5850],
         [0.1511, 0.7076, 0.0791, 0.4569],
         [0.5119, 0.9318, 0.5983, 0.4627]]])

In [9]:
rand_tensor_2.ndim
rand_tensor_2.shape

torch.Size([3, 3, 4])

In [10]:
# example 2 of random tensor
# standard img [224,224,3]: [width, height, color_channel]
rand_img_tensor=torch.rand(size=(224,224,3))
rand_img_tensor

tensor([[[0.2724, 0.3902, 0.1595],
         [0.1505, 0.5626, 0.9745],
         [0.5399, 0.2079, 0.4152],
         ...,
         [0.0196, 0.2881, 0.5975],
         [0.6785, 0.9082, 0.4116],
         [0.0393, 0.6334, 0.7755]],

        [[0.1915, 0.2422, 0.4833],
         [0.5281, 0.7180, 0.9370],
         [0.5768, 0.1800, 0.8801],
         ...,
         [0.2146, 0.4035, 0.8731],
         [0.2771, 0.9641, 0.6929],
         [0.6018, 0.2822, 0.1791]],

        [[0.2416, 0.2511, 0.8519],
         [0.4881, 0.5723, 0.6234],
         [0.1367, 0.1981, 0.0636],
         ...,
         [0.7895, 0.3810, 0.5848],
         [0.3855, 0.3486, 0.6789],
         [0.4321, 0.3299, 0.7174]],

        ...,

        [[0.7110, 0.2791, 0.3096],
         [0.3835, 0.8239, 0.8381],
         [0.0483, 0.1104, 0.6222],
         ...,
         [0.2071, 0.1202, 0.8483],
         [0.3726, 0.8794, 0.9036],
         [0.5699, 0.2263, 0.4644]],

        [[0.3351, 0.7622, 0.3334],
         [0.5197, 0.5968, 0.9132],
         [0.

In [11]:
# properties
# dimention
# it's a 3 D tensor
rand_img_tensor.ndim
rand_img_tensor.shape

torch.Size([224, 224, 3])

#Zeros and Ones

In [12]:
# sometimes, we need to fill tensors with zeros and ones
# torch.zeros(), torch.ones() plays a crucial role into it

zeros_1=torch.zeros(size=(3,4))
zeros_1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones_1=torch.ones(size=(3,4))
ones_1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# default datatype of tensor is float32
zeros_1.dtype, ones_1.dtype

(torch.float32, torch.float32)

#Creating a range and Tensor like

In [15]:
# for creating range tensor
# torch.arange(start, stop, step) is being used
# torch.arange() will return 1D tensor
range_1=torch.arange(0,11,2)
range_1
range_1.ndim
range_1.shape


torch.Size([6])

In [16]:
# sometimes, we want a tensor of certain type with same shape as another type
# for that, we have zeros_like, ones_like

zeros_like_1=torch.zeros_like(input=range_1)
zeros_like_1

tensor([0, 0, 0, 0, 0, 0])

In [17]:
ones_like_1=torch.ones_like(input=range_1)
ones_like_1

tensor([1, 1, 1, 1, 1, 1])

#Tensor datatypes

In [18]:
# in Tensor, default datatype if float32 (or whatever we've used)
float_32_tensor=torch.tensor([1,2,3],dtype=torch.float32,#default is float32, else whatever we've used
                             device=None, #default none, or which uses default tensor type
                             requires_grad=False #if True, operations performed on tensor are recorded
                             )

float_32_tensor.dtype
float_32_tensor.device

device(type='cpu')

In [19]:
float_16_tensor=torch.tensor([1,2,3],dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [20]:
# getting information from tensors
tensor_1=torch.rand(size=(3,4))
tensor_1

tensor([[0.6890, 0.8546, 0.7691, 0.2114],
        [0.4862, 0.5326, 0.9436, 0.2626],
        [0.6800, 0.0884, 0.4417, 0.1797]])

In [21]:
# information of tensor_1
tensor_1.shape
tensor_1.dtype
tensor_1.device #the device on which, tensor_1 is stored on

device(type='cpu')

#Manipulating Tensors

In [22]:
# we can perform many operations on tensors like
# addition, multiplication, division, substraction, matrix multiplication etc

# multiplication
tensor=torch.tensor([1,2,3])
tensor
# multiplying with 10
tensor*10
# acutal tensor didn't change
tensor

tensor([1, 2, 3])

In [23]:
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [24]:
tensor=tensor+10
tensor

tensor([1, 2, 3])

In [25]:
# another method for multiplying tensor
mul_tensor=torch.tensor([1,2,3])
torch.multiply(mul_tensor,10)
# it'll show the result of operation

# original tensor
mul_tensor

tensor([1, 2, 3])

In [26]:
# matrix multiplication
matrix_multi_tensor=torch.tensor([1,2,3])
matrix_multi_tensor

tensor([1, 2, 3])

In [27]:
# element wise multiplication of 'matrix_multi_tensor'
matrix_multi_tensor*matrix_multi_tensor

tensor([1, 4, 9])

In [28]:
# matrix wise multiplication
# method 1
torch.matmul(matrix_multi_tensor,matrix_multi_tensor)

# method 2
# @ used for matrix multiplication
matrix_multi_tensor@matrix_multi_tensor

tensor(14)

In [29]:
# matrix multiplication time taken from loop and from matmul

%%time
value=0
for i in range(len(matrix_multi_tensor)):
  value+=matrix_multi_tensor[i]*matrix_multi_tensor[i]
value

UsageError: Line magic function `%%time` not found.


In [ ]:
# using torch.matmul()
%%time
torch.matmul(matrix_multi_tensor, matrix_multi_tensor)

CPU times: user 333 µs, sys: 0 ns, total: 333 µs
Wall time: 281 µs


tensor(14)

In [ ]:
# matrix multiplication in Tensor
tensor_A=torch.rand(size=(3,2))
tensor_A

tensor([[0.0109, 0.4912],
        [0.8006, 0.0867],
        [0.9048, 0.4482]])

In [ ]:
tensor_B=torch.rand(size=(3,2))
tensor_B

tensor([[0.4105, 0.2026],
        [0.9062, 0.2846],
        [0.4656, 0.3088]])

In [ ]:
# shape,size of tensor_A, tensor_B
tensor_A.shape
tensor_B.shape

torch.Size([3, 2])

In [ ]:
# matrix multiplication of tensor_A, tensor_B
# same size of matrix multiplication will throw error
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# changing tensor_B's shape
tensor_C=tensor_B.T
tensor_C

tensor([[0.4105, 0.9062, 0.4656],
        [0.2026, 0.2846, 0.3088]])

In [ ]:
tensor_C.shape

torch.Size([2, 3])

In [ ]:
# matrix multiplication of tensor_A, tensor_C
torch.matmul(tensor_A, tensor_C)


tensor([[0.1040, 0.1497, 0.1567],
        [0.3462, 0.7502, 0.3995],
        [0.4622, 0.9475, 0.5597]])

In [ ]:
# some special cases try
# we'll come into it in later parts
torch.manual_seed(42)
# This is used for matrix multiplication
linear=torch.nn.Linear(in_features=2, # in_feature: matches the inner dimention of input
                       out_features=6 # out_features: describe other values
                       )
X=tensor_A
print(X.shape)
output=linear(X)
print(output)
print(output.shape)

torch.Size([3, 2])
tensor([[ 0.8166,  0.4130,  0.4094,  0.1004,  0.2971,  0.1762],
        [ 1.0061,  0.0194,  0.2293, -0.3395,  0.9992,  0.6081],
        [ 1.2746,  0.2370,  0.2647, -0.2252,  0.8767,  0.7200]],
       grad_fn=<AddmmBackward0>)
torch.Size([3, 6])


#Finding min, max, mean etc...

In [ ]:
# finding min
x=torch.arange(1,11,0.5)
print(x)
# max value
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000])
tensor(1.)
tensor(10.5000)
tensor(5.7500)
tensor(115.)


In [ ]:
# above examples in another way
torch,min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(<module 'torch' from '/usr/local/lib/python3.12/dist-packages/torch/__init__.py'>,
 tensor(1.),
 tensor(10.5000),
 tensor(5.7500),
 tensor(115.))

In [ ]:
# we can also find positional min, max (index at where min, max value appeared)
print(x.argmax())
print(x.argmin())

tensor(19)
tensor(0)


#Reshape, stack, squeez, unsqueez

In [ ]:
# the need of reshaping
t1=torch.arange(1,7,dtype=torch.float32)
print(t1)
print(t1.shape)

# reshaping tensor t1
t2=t1.reshape(1,6)
print(t2)
print(t2.shape)

t3=t1.reshape(2,3)
print(t3)
print(t3.shape)

t4=t1.reshape(3,2)
print(t4)
print(t4.shape)


tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])
tensor([[1., 2., 3., 4., 5., 6.]])
torch.Size([1, 6])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([1., 2., 3., 4., 5., 6.])


In [ ]:
# another method similar to reshape
z=t1.view(1,6)
print(z)
print(z.shape)

# but for t1
print(t1)
print(t1.shape)

tensor([[1., 2., 3., 4., 5., 6.]])
torch.Size([1, 6])
tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])


In [ ]:
# changing the value of z
# method 1
print(z[0][0])
# method 2
print(z[:,0])

tensor(1.)
tensor([1.])


In [ ]:
# changin value
# changing the view (z), also change (x)
z[:,0]=5
print(z)
print(t1)

tensor([[5., 2., 3., 4., 5., 6.]])
tensor([5., 2., 3., 4., 5., 6.])


In [ ]:
# stacking tensor one upon one
x_1=torch.arange(1,6, dtype=torch.float32)
print(x_1)
x_1_stacked=torch.stack([x_1,x_1,x_1],dim=1)
print(x_1_stacked)
print(x_1_stacked.shape)

tensor([1., 2., 3., 4., 5.])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.]])
torch.Size([5, 3])


In [ ]:
# torch.squeez()
# it removes 1 dimention from tensor
pre_squeez=torch.rand(size=(1,3,5))
print(pre_squeez)
print(pre_squeez.shape)

post_squeez=pre_squeez.squeeze()
print(post_squeez)
print(post_squeez.shape)

tensor([[[0.6790, 0.9155, 0.2418, 0.1591, 0.7653],
         [0.2979, 0.8035, 0.3813, 0.7860, 0.1115],
         [0.2477, 0.6524, 0.6057, 0.3725, 0.7980]]])
torch.Size([1, 3, 5])
tensor([[0.6790, 0.9155, 0.2418, 0.1591, 0.7653],
        [0.2979, 0.8035, 0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057, 0.3725, 0.7980]])
torch.Size([3, 5])


In [ ]:
# we can add extra 1 dimention with unsqueez
print(post_squeez)
print(post_squeez.shape)
post_unsqueeze=post_squeez.unsqueeze(dim=0)
print(post_unsqueeze)
print(post_unsqueeze.shape)

tensor([[0.6790, 0.9155, 0.2418, 0.1591, 0.7653],
        [0.2979, 0.8035, 0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057, 0.3725, 0.7980]])
torch.Size([3, 5])
tensor([[[0.6790, 0.9155, 0.2418, 0.1591, 0.7653],
         [0.2979, 0.8035, 0.3813, 0.7860, 0.1115],
         [0.2477, 0.6524, 0.6057, 0.3725, 0.7980]]])
torch.Size([1, 3, 5])


In [ ]:
# in Tensor, we can change the axis
x_original=torch.rand(size=(224,224,3))
# print(x_original)
print(x_original.shape)
# 0->1, 1->2, 2->0 changes
x_permuted=x_original.permute(2,0,1)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


#Indexing

In [ ]:
# selecting a data from tensor
x=torch.rand(size=(1,3,3))
print(x)
print(x[0][0][1])
print(x[0][2][2])
print(x[:,:,1])
print(x[:,0,1])

tensor([[[0.5066, 0.6647, 0.6705],
         [0.7198, 0.9719, 0.2247],
         [0.3770, 0.1259, 0.5085]]])
tensor(0.6647)
tensor(0.5085)
tensor([[0.6647, 0.9719, 0.1259]])
tensor([0.6647])


#PyTorch Tensors & Numpy

In [ ]:
# both Numpy, PyTorch is used in computing
# we can change a numpy array into tensor
# or a tensor into array

import numpy as np
np_array=np.arange(1,6)
print(np_array)
torch_tensor=torch.arange(1,6)
print(torch_tensor)

[1 2 3 4 5]
tensor([1, 2, 3, 4, 5])


In [ ]:
# changing np_array into tensor
# torch.form_numpy(ndarray): change nd_array into tensor
# by defau;t numpy array has data of float64
# for pytorch, we need to convert it into float32
np_array_tensor=torch.from_numpy(np_array).type(torch.float32)
print(np_array_tensor)

tensor([1., 2., 3., 4., 5.])


In [ ]:
# from pytorch tensor to numpy ndarray
py_tensor=torch.rand(size=(5,))
print(py_tensor)

tensor([0.0551, 0.8775, 0.1657, 0.4708, 0.2254])


In [ ]:
# changing py_tensor into nd_array, using 'tensor_name'.numpy()
numpy_tensor=py_tensor.numpy()
print(numpy_tensor)

[0.05508381 0.8775488  0.16571355 0.47083282 0.22542948]


#Reproducibility

In [ ]:
# Reproducibility
# Let's take an example
# let say, you make any code, that code runs on your system well, and your frined, wanted to try it out on his/her system
# but what if, your code gives a result in your system, but give different result on your friends system
# to tackle this isse, reproducibility, come into play.
# it makes result stable

# example
random_tensor_1=torch.rand(size=(3,3))
print(random_tensor_1)

# output is always different of random_tensor_1 & random_tensor_2

random_tensor_2=torch.rand(size=(3,3))
print(random_tensor_2)

tensor([[0.6757, 0.0170, 0.1077],
        [0.2836, 0.9033, 0.0818],
        [0.2888, 0.7516, 0.3333]])
tensor([[0.8353, 0.2945, 0.7621],
        [0.7084, 0.3098, 0.1923],
        [0.5105, 0.1072, 0.0307]])


In [ ]:
# by initializing random_seed, we can stabilize this result
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_3=torch.rand(size=(3,3))

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_4=torch.rand(size=(3,3))

print(random_tensor_3)
print(random_tensor_4)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [ ]:
torch.cuda.is_available()

False